### ISSUE TITLE
Can't cancel sear.

### ISSUE THREAD

**Issue by HairyHog** [calware/BetterChef#2]
I've tried holding, I've tried pressing and then pressing again to toggle off, doesn't work. Tried with and without any other mods too, something's up.

**Comment by calware** [comment]
Hey! Thanks for your comment :)
This issue was solved with release 1.0.2 (commit reference 302e3dc). For right now, you have to hold down the Sear activation key for as long as you'd like Sear to continue for, though tonight a change is coming that will make Sear a toggle (if you configure it to do so).
